{
	"version": 1539864279,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/personagem1-sheet0.png",
		"images/personagem1-sheet1.png",
		"images/personagem1-sheet2.png",
		"images/inimigo1-sheet0.png",
		"images/inimigo1-sheet1.png",
		"images/chão-sheet0.png",
		"images/chave-sheet0.png",
		"images/recptordachave-sheet0.png",
		"images/parede2-sheet0.png",
		"images/elevador1-sheet0.png",
		"images/portal-sheet0.png",
		"images/bg-sheet0.png",
		"images/fundosplash-sheet0.png",
		"images/caneca-sheet0.png",
		"images/lápis-sheet0.png",
		"images/nome-sheet0.png",
		"images/gameover-sheet0.png",
		"images/bmenu-sheet0.png",
		"images/brecomeca-sheet0.png",
		"images/telainicial-sheet0.png",
		"images/telainicial-sheet1.png",
		"images/telainicial-sheet2.png",
		"images/telainicial-sheet3.png",
		"images/telainicial-sheet4.png",
		"images/bnovojogo-sheet0.png",
		"images/bopcao-sheet0.png",
		"images/bcreditos-sheet0.png",
		"images/credito-sheet0.png",
		"images/opcoes-sheet0.png",
		"images/bdesligado-sheet0.png",
		"images/bligado-sheet0.png",
		"images/back2-sheet0.png",
		"images/back3-sheet0.png",
		"images/corfundo-sheet0.png",
		"images/estranho-sheet0.png",
		"images/dialogo-sheet0.png",
		"images/lo-sheet0.png",
		"images/brilhoio-sheet0.png",
		"images/pausa-sheet0.png",
		"images/volarjogo-sheet0.png",
		"images/chao-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/plataformagrande-sheet0.png",
		"images/inimigo2-sheet0.png",
		"images/inimigo2-sheet1.png",
		"images/inimigo3-sheet0.png",
		"images/inimigo4-sheet0.png",
		"images/inimigo4-sheet1.png",
		"images/poderlobo-sheet0.png",
		"images/colecionaveis-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sensorlobo-sheet0.png",
		"images/sensormago-sheet0.png",
		"images/sensormago1-sheet0.png",
		"images/chao1-sheet0.png",
		"images/bpersona-sheet0.png",
		"images/barradecima-sheet0.png",
		"images/barradebaixo-sheet0.png",
		"images/fade-sheet0.png",
		"images/carregando-sheet0.png",
		"images/fogo-sheet0.png",
		"images/fogo-sheet1.png",
		"images/sprite7-sheet0.png",
		"images/botãosom-sheet0.png",
		"images/botãomusica-sheet0.png",
		"images/botãot-sheet0.png",
		"images/chave2-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/portafase2-sheet0.png",
		"media/dantes inferno soundtrack - track 40 - redemption.ogg",
		"media/intro e transição pack 2 efeito sonoro grátis e sem copyright (online-audio-converter.com).ogg",
		"media/trilha Épica de ação 1  efeito sonoro grátis e sem copyright.ogg",
		"media/pulo.ogg",
		"media/ataque darksaber.ogg",
		"media/lobo correndo.ogg",
		"media/fase 2.ogg",
		"media/seleçã.m4a",
		"media/seleçã.ogg",
		"media/darksaber andando.ogg",
		"media/mago ataque.ogg",
		"media/ataque foice.ogg",
		"media/spctro andando.ogg",
		"media/ataque fogo.ogg",
		"media/ataque gelo.ogg",
		"media/corrida.ogg",
		"media/dano.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}